class Defaults:
    DEFAULT_MODEL_STORE_FILE_NAME = "file_metadata.json"
    DEFAULT_NOTES_FILE_NAME = "my_first_file.txt"
    DEFAULT_SECTION_FILE_SEPARATOR = "<section={name}> "
    DEFAULT_SECTION_FILE_SEPARATOR_REGEX = "<section=[a-z A-Z0-9]+> "
    DEFAULT_SECTION_FILE_SEPARATOR_GROUP_SUBSTR_REGEX = "<section=(.+?)> "
    DEFAULT_NOTES_FILE_CONTENT = f"{DEFAULT_SECTION_FILE_SEPARATOR.format(name='first')} Your first section. Here you can write your notes."
    DEFAULT_AUTO_SAVE_TEXT_INPUT_CHANGE_COUNT = 5
    DEFAULT_VALUE_SEARCH_CASE_SENSITIVE = False
    DEFAULT_VALUE_SEARCH_ALL_SECTIONS = False
    DEFAULT_VALUE_SEARCH_FULL_WORDS = False
    DEFAULT_SETTINGS_STORE_FILE_NAME = "settings.json"
    DEFAULT_SETTINGS_VALUE_FONT_NAME = "RobotoMono-Regular"
    DEFAULT_SETTINGS_VALUE_FONT_SIZE = "14.0"
    DEFAULT_SETTINGS_VALUE_BACKGROUND_COLOR = "black"
    DEFAULT_SETTINGS_VALUE_FOREGROUND_COLOR = "green"
